drop policy if exists "Public can view games" on public.games;
drop policy if exists "Anyone can read games" on public.games;
drop policy if exists "Authenticated can insert games" on public.games;
drop policy if exists "Authenticated can update games" on public.games;
drop policy if exists "Authenticated can delete games" on public.games;
create policy "Public can view games" on public.games for select to anon, authenticated using (true);
create policy "Authenticated can insert games" on public.games for insert to authenticated with check (true);
create policy "Authenticated can update games" on public.games for update to authenticated using (true) with check (true);
create policy "Authenticated can delete games" on public.games for delete to authenticated using (true);
drop policy if exists "Public can view game images" on storage.objects;
drop policy if exists "Authenticated can upload game images" on storage.objects;
drop policy if exists "Authenticated can update game images" on storage.objects;
drop policy if exists "Authenticated can delete game images" on storage.objects;
create policy "Public can view game images" on storage.objects for select to public using (bucket_id='game-images');
create policy "Authenticated can upload game images" on storage.objects for insert to authenticated with check (bucket_id='game-images');
create policy "Authenticated can update game images" on storage.objects for update to authenticated using (bucket_id='game-images') with check (bucket_id='game-images');
create policy "Authenticated can delete game images" on storage.objects for delete to authenticated using (bucket_id='game-images');