"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {supabase} from "../lib/supabase";
const BUCKET="game-images";

function Header({email}){return <header className="topbar"><div className="brand"><div className="brand-mark">S</div><div><div className="brand-title">GAME CATALOG</div><div className="brand-subtitle">{email||"Управление коллекцией"}</div></div></div><div style={{display:"flex",gap:8}}>{email&&<button className="secondary-btn" onClick={()=>supabase.auth.signOut()}>Выйти</button>}<Link className="admin-link" href="/">← К каталогу</Link></div></header>}

export default function AdminPanel(){
 const [session,setSession]=useState(null),[checked,setChecked]=useState(false),[games,setGames]=useState([]),[editing,setEditing]=useState(null),[file,setFile]=useState(null),[preview,setPreview]=useState(""),[msg,setMsg]=useState(""),[err,setErr]=useState(""),[dragged,setDragged]=useState(null);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setChecked(true)});const {data:l}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>l.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)load()},[session]);
 async function load(){const {data,error}=await supabase.from("games").select("*").order("sort_order",{ascending:true}).order("created_at",{ascending:true});if(error)setErr(error.message);else setGames(data||[])}
 function reset(){setEditing(null);setFile(null);setPreview("");document.getElementById("gameForm")?.reset();setMsg("");setErr("")}
 function start(g){setEditing(g);setFile(null);setPreview(g.image_url);document.getElementById("title").value=g.title;document.getElementById("steam_url").value=g.steam_url;document.getElementById("description").value=g.description;scrollTo({top:0,behavior:"smooth"})}
 async function upload(f){const name=f.name.toLowerCase().replace(/[^a-z0-9._-]+/g,"-");const path=`${crypto.randomUUID()}-${name}`;const {error}=await supabase.storage.from(BUCKET).upload(path,f,{cacheControl:"3600",upsert:false});if(error)throw error;return supabase.storage.from(BUCKET).getPublicUrl(path).data.publicUrl}
 function oldPath(url){const m=`/storage/v1/object/public/${BUCKET}/`;const i=url.indexOf(m);return i>=0?decodeURIComponent(url.slice(i+m.length)):null}
 async function removeImage(url){const p=oldPath(url);if(p)await supabase.storage.from(BUCKET).remove([p])}
 async function save(e){e.preventDefault();setErr("");setMsg("");const f=e.currentTarget,title=f.title.value.trim(),steam_url=f.steam_url.value.trim(),description=f.description.value.trim();try{new URL(steam_url)}catch{return setErr("Укажи корректную ссылку Steam.")}try{let image_url=editing?.image_url||"";const old=editing?.image_url||null;if(file)image_url=await upload(file);if(editing){const {error}=await supabase.from("games").update({title,steam_url,description,image_url}).eq("id",editing.id);if(error)throw error;if(file&&old)await removeImage(old);setMsg("Игра обновлена.")}else{const sort_order=games.length?Math.max(...games.map(x=>x.sort_order||0))+1:0;const {error}=await supabase.from("games").insert({title,steam_url,description,image_url,sort_order});if(error)throw error;setMsg("Игра добавлена.")}setEditing(null);setFile(null);setPreview("");f.reset();await load()}catch(x){setErr(x.message||"Ошибка сохранения.")}}
 async function del(g){if(!confirm(`Удалить «${g.title}»?`))return;const {error}=await supabase.from("games").delete().eq("id",g.id);if(error)return setErr(error.message);await removeImage(g.image_url);await load();setMsg("Игра удалена.")}
 async function drop(target){if(!dragged||dragged===target)return;const a=games.findIndex(x=>x.id===dragged),b=games.findIndex(x=>x.id===target);const arr=[...games],m=arr.splice(a,1)[0];arr.splice(b,0,m);setGames(arr);setDragged(null);const r=await Promise.all(arr.map((x,i)=>supabase.from("games").update({sort_order:i}).eq("id",x.id)));const bad=r.find(x=>x.error);if(bad){setErr(bad.error.message);load()}else setMsg("Порядок игр сохранён.")}
 if(!checked)return <div className="empty"><p>Проверяем авторизацию…</p></div>;
 if(!session)return <><Header/><main className="admin-container"><section className="hero"><p className="eyebrow">ADMIN</p><h1>Вход</h1><p className="hero-text">Раздел управления доступен только владельцу каталога.</p></section><Login/></main></>;
 return <><Header email={session.user.email}/><main className="admin-container"><section className="hero"><p className="eyebrow">ADMIN</p><h1>Добавить игру</h1><p className="hero-text">Добавляй игры, загружай картинки и перетаскивай их для изменения порядка.</p></section>
 <section className="panel"><form id="gameForm" onSubmit={save}><div className="form-grid"><label>Название игры<input id="title" name="title" required/></label><label>Ссылка на Steam<input id="steam_url" name="steam_url" type="url" required/></label><label className="full">Описание<textarea id="description" name="description" required/></label><label className="full upload-box">Изображение<input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0]||null;setFile(f);if(f)setPreview(URL.createObjectURL(f))}}/><span className="hint">PNG, JPG, WEBP.</span>{preview&&<img className="preview" src={preview} alt="Предпросмотр"/>}</label></div><div className="form-actions"><button className="primary-btn">{editing?"Сохранить изменения":"Добавить игру"}</button>{editing&&<button type="button" className="secondary-btn" onClick={reset}>Отмена</button>}</div>{msg&&<p className="message" style={{color:"var(--success)"}}>{msg}</p>}{err&&<p className="message" style={{color:"var(--danger)"}}>{err}</p>}</form></section>
 <section className="panel"><div className="panel-heading"><div><p className="eyebrow">COLLECTION</p><h2>Мои игры</h2></div><span className="admin-number">{games.length}</span></div><div className="admin-list">{games.map((g,i)=><div key={g.id} className="admin-item" draggable onDragStart={()=>setDragged(g.id)} onDragOver={e=>e.preventDefault()} onDrop={()=>drop(g.id)}><div className="drag-handle">⠿</div><img className="admin-thumb" src={g.image_url} alt={g.title}/><div className="admin-info"><div className="admin-number">{i+1}</div><h3>{g.title}</h3><p>{g.description}</p></div><div className="item-actions"><button className="secondary-btn" onClick={()=>start(g)}>Изменить</button><button className="danger-btn" onClick={()=>del(g)}>Удалить</button></div></div>)}</div></section></main></>
}
function Login(){const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(false);async function submit(e){e.preventDefault();setLoading(true);setError("");const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setError(error.message);setLoading(false)}return <section className="panel login"><form onSubmit={submit}><div className="form-grid" style={{gridTemplateColumns:"1fr"}}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Пароль<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label></div><div className="form-actions"><button className="primary-btn" disabled={loading}>{loading?"Входим…":"Войти"}</button></div>{error&&<p className="message" style={{color:"var(--danger)"}}>{error}</p>}</form></section>}
